#!/usr/bin/env bash
# template-digest.sh — give the vended template a VERSION, and make a change to
# it something a human has to acknowledge.
#
# TWO GAPS, ONE MECHANISM.
#
# 1. CONSUMERS COULD NOT PIN A VERSION. A scaffolded repo records which files it
#    vendored and what each hashed, and for the version it records
#    `stamped_from: production-skills@unknown`. Not sometimes -- ALWAYS, and by
#    construction: the stamper resolved it with `git -C
#    ${CLAUDE_CONFIG_DIR}/skills/prod-new rev-parse HEAD`, and that directory is
#    a hash-verified COPY made by install.sh, not a git work tree. Measured
#    2026-08-30: `fatal: not a git repository`. A field that looks answered and
#    says nothing is worse than an absent one.
#
# 2. NOTHING CHECKED THE PRODUCER SIDE. `check-template-drift.sh` runs in the
#    scaffolded repo and answers "am I behind?". Here, in the repo that MOVES the
#    template, nothing asked "did the vended surface just change?" -- so it could
#    change in a commit nobody labelled as touching downstream repos.
#
# The version is a CONTENT DIGEST over the vendored set, not a tag or a hand-kept
# number, for one reason: a number somebody has to remember to bump is a number
# that goes stale silently, and a stale version is the same lie as `unknown`
# wearing a plausible face. A digest cannot be forgotten -- change a vendored
# file and it changes.
#
# THE FILE LIST IS EXTRACTED FROM stamp-template-provenance.sh, never copied.
# Two lists of the same thing is a denominator that rots: one grows, the other
# does not, and the check silently covers less than it claims.
#
# Usage:
#   template-digest.sh            compare the committed digest against reality (gate)
#   template-digest.sh --write    recompute and write it (after a reviewed change)
# Exit: 0 in step · 1 the vended surface moved · 2 refused to answer
set -uo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.." || exit 2

STAMPER="prod-new/template/scripts/stamp-template-provenance.sh"
TPL="prod-new/template"
DIGEST_FILE="prod-new/TEMPLATE-DIGEST"

[[ -r "$STAMPER" ]] || { echo "template-digest: cannot read $STAMPER" >&2; exit 2; }

mapfile -t FILES < <(sed -n '/^VENDORED=(/,/^)/p' "$STAMPER" \
  | grep -vE '^VENDORED=\(|^\)' | sed 's/#.*//' | tr -d ' \t' | grep -v '^$')

if (( ${#FILES[@]} == 0 )); then
  echo "template-digest: extracted ZERO vendored files from $STAMPER." >&2
  echo "  A digest over nothing is a constant that never changes, which would report" >&2
  echo "  'in step' for every future edit to the template. Refusing." >&2
  exit 2
fi

# MISSING FILES ARE A FAILURE, not a skipped line. A vendored file that no longer
# exists means the list and the tree disagree, and hashing what remains would
# produce a digest that looks fine while describing a set nobody has.
missing=()
for f in "${FILES[@]}"; do [[ -f "$TPL/$f" ]] || missing+=("$f"); done
if (( ${#missing[@]} > 0 )); then
  echo "template-digest: ${#missing[@]} vendored file(s) named in $STAMPER do not exist:" >&2
  printf '  missing: %s\n' "${missing[@]}" >&2
  echo "  Either the file moved and the list is stale, or it was deleted and downstream" >&2
  echo "  repos still vendor it. Both need a human." >&2
  exit 2
fi

# Sorted by path so the digest depends on CONTENT and membership, never on the
# order somebody happened to type the list in.
digest=$(for f in $(printf '%s\n' "${FILES[@]}" | sort); do
           printf '%s  %s\n' "$(shasum -a 256 "$TPL/$f" | awk '{print $1}')" "$f"
         done | shasum -a 256 | awk '{print $1}')
short="${digest:0:12}"

if [[ "${1:-}" == "--write" ]]; then
  {
    printf '# TEMPLATE DIGEST — the version a scaffolded repo pins to.\n'
    printf '#\n'
    printf '# Generated by scripts/template-digest.sh --write. Do not hand-edit: it is a\n'
    printf '# content hash over the %d files stamp-template-provenance.sh declares as\n' "${#FILES[@]}"
    printf '# vendored, sorted by path. Editing it by hand certifies a template nobody has.\n'
    printf '#\n'
    printf '# When this changes, EVERY repo scaffolded from an older template is behind.\n'
    printf '# That is the point: the change has to be acknowledged in the commit that\n'
    printf '# makes it, rather than discovered by whoever scaffolds next.\n'
    printf 'digest: %s\n' "$digest"
    printf 'short: %s\n' "$short"
    printf 'files: %d\n' "${#FILES[@]}"
    printf 'per_file:\n'
    for f in $(printf '%s\n' "${FILES[@]}" | sort); do
      printf '  %s: %s\n' "$f" "$(shasum -a 256 "$TPL/$f" | awk '{print $1}')"
    done
  } > "$DIGEST_FILE"
  echo "template-digest: wrote $DIGEST_FILE -- $short over ${#FILES[@]} vendored file(s)"
  exit 0
fi

if [[ ! -f "$DIGEST_FILE" ]]; then
  echo "template-digest: no $DIGEST_FILE -- the vended template has no version," >&2
  echo "  so no scaffolded repo can pin one. Run: make template-digest" >&2
  exit 1
fi

recorded=$(awk '/^digest:/{print $2}' "$DIGEST_FILE")
[[ -n "$recorded" ]] || { echo "template-digest: $DIGEST_FILE has no digest: line" >&2; exit 2; }

if [[ "$recorded" == "$digest" ]]; then
  echo "template-digest: in step -- $short over ${#FILES[@]} vendored file(s)"
  exit 0
fi

echo "template-digest: THE VENDED TEMPLATE CHANGED and the digest was not updated." >&2
echo "  recorded: ${recorded:0:12}" >&2
echo "  actual:   $short" >&2
# NAME THE FILES, because a digest that only says "something moved" sends the
# reader to diff sixteen files by hand. The per_file block exists for exactly
# this moment.
# A DIGEST FILE WITH NO per_file BLOCK cannot name anything, and saying so is the
# honest answer. Without this guard every file reads as ADDED -- `was` is empty
# for all of them -- so an old digest produced a list of sixteen bogus additions
# that hid the one real change. Found by mutating this script and watching the
# selftest's ADDED case pass for the wrong reason.
if ! grep -q '^per_file:' "$DIGEST_FILE" 2>/dev/null; then
  echo "    (this digest predates the per_file block, so which files moved cannot be" >&2
  echo "     named -- regenerate with \`make template-digest\` to get that back)" >&2
  echo "  Every repo scaffolded from the previous template is now behind." >&2
  exit 1
fi

changed=0
for f in $(printf '%s\n' "${FILES[@]}" | sort); do
  was=$(grep -E "^  $(printf '%s' "$f" | sed 's/[][\.*^$/]/\\&/g'): " "$DIGEST_FILE" 2>/dev/null | awk '{print $2}')
  now=$(shasum -a 256 "$TPL/$f" | awk '{print $1}')
  if [[ -z "$was" ]]; then
    echo "    ADDED    $f" >&2; changed=$((changed+1))
  elif [[ "$was" != "$now" ]]; then
    echo "    CHANGED  $f  ${was:0:12} -> ${now:0:12}" >&2; changed=$((changed+1))
  fi
done
while IFS= read -r rec; do
  [[ -n "$rec" ]] || continue
  printf '%s\n' "${FILES[@]}" | grep -qxF "$rec" || { echo "    REMOVED  $rec" >&2; changed=$((changed+1)); }
done < <(sed -n '/^per_file:/,$p' "$DIGEST_FILE" | grep -E '^  [^ ]+: ' | sed 's/^  //; s/:.*//')
(( changed > 0 )) || echo "    (no per-file difference found -- the recorded digest predates the per_file block)" >&2
echo "  Every repo scaffolded from the previous template is now behind. Acknowledge it" >&2
echo "  in this commit: run \`make template-digest\` and say in the message what" >&2
echo "  downstream repos have to do about it." >&2
exit 1
