package eventlog

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/<OWNER>/<SERVICE>/internal/domain"
)

// provenance: derived
// verifies: compatibility (tier-policy: compatibility.schema = expand_contract,
// breaking_check required) -- a GOLDEN fixture of the on-disk record format,
// so a future field rename/removal is caught here instead of silently
// changing what an already-written production log means. This is an N-1
// check: a log written by an OLDER build of this schema_version must still
// Replay correctly under the CURRENT code.
func TestEventlog_GoldenRecordFormatIsStillReadable(t *testing.T) {
	golden := filepath.Join("testdata", "golden_v1.jsonl")
	data, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}
	path := filepath.Join(t.TempDir(), "replay.jsonl")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write temp copy: %v", err)
	}

	events, err := Replay(path)
	if err != nil {
		t.Fatalf("Replay(golden fixture): %v", err)
	}
	want := []domain.Event{
		{ID: "golden-1", Type: domain.EventDeposited, Amount: "42.5"},
		{ID: "golden-2", Type: domain.EventWithdrawn, Amount: "10"},
	}
	if len(events) != len(want) {
		t.Fatalf("got %d events from the golden fixture, want %d", len(events), len(want))
	}
	for i := range want {
		if events[i] != want[i] {
			t.Fatalf("golden event %d = %+v, want %+v -- the wire format has drifted from schema_version %d's committed shape", i, events[i], want[i], SchemaVersion)
		}
	}
}

// provenance: derived
// verifies: compatibility (tier-policy: compatibility.schema =
// expand_contract) for schema_version 2 -- the shape that introduced the
// `kind` discriminator and snapshot records.
//
// This fixture was GENERATED by the real writer, not typed by hand, so it
// records what this package actually produces rather than what someone
// believed it produced. Editing it to make a test pass would erase the only
// evidence of what v2 looked like on disk; a format change gets a v3
// fixture beside this one.
func TestEventlog_GoldenV2SnapshotFormatIsStillReadable(t *testing.T) {
	golden := filepath.Join("testdata", "golden_v2.jsonl")
	data, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}
	path := filepath.Join(t.TempDir(), "replay.jsonl")
	if err := os.WriteFile(path, data, 0o644); err != nil {
		t.Fatalf("write temp copy: %v", err)
	}

	state, stats, err := Recover(path)
	if err != nil {
		t.Fatalf("Recover(golden v2): %v", err)
	}
	if !stats.SnapshotFound {
		t.Fatal("the v2 fixture contains a snapshot record that Recover did not use")
	}
	if stats.EventsReplayed != 1 {
		t.Errorf("EventsReplayed = %d, want 1 (only the event after the snapshot)", stats.EventsReplayed)
	}
	// 42.5 - 10 (subsumed by the snapshot) + 1 (replayed after it)
	if state.Balance != "33.50000000" {
		t.Fatalf("balance = %q, want 33.50000000 -- the v2 wire format has drifted from "+
			"its committed shape", state.Balance)
	}
	if state.Version != 3 {
		t.Errorf("version = %d, want 3", state.Version)
	}
}
